---
title: "Coding Projects"
---

We have prepared several projects to work on in groups on the second and third
day of the workshop.

## Multimodal Met Museum Semantic Networks

Connects artworks from the Metropolitan Museum of Art Open Access API to their
shared semantic concepts (extracted using Gemini) into an interactive network
visualization.

[Project plan](archival-collections/)

<!-- 
## Geospatial Data Vibe Visualizing

An exploratory analysis using geospatial data in R to visualize and overlay
19th-century wildfires against other relevant records.

[Project plan](geo-viz/) 
-->

## The Bikeability of Santa Barbara County

Computes the steepness of Santa Barbara County using a Digital Elevation Model
(DEM) and US Census Group Blocks to create a map showing the median slope of
each area.

[Project plan](bikability/)

## The Fish Abundance in the Kelp Forests of the Santa Barbara Channel

This project explores two decades of long-term fish density data in the Santa Barbara Channel kelp forests to uncover species dominance, population trends over time, and the ecological impact of Marine Protected Areas.

[Project plan](fish/)

## Propose your own data exploration project!

Perhaps you already have a project in mind, or you'd prefer a more open-ended
exploration of a dataset. You'll have an opportunity (**on the second day of the
workshop**) to "pitch" a group project idea. 
