project:
  type: website

website:
  title: "AI-Assisted Coding for Research"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: setup.qmd
        text: Setup
      - text: Lessons
        menu:
          - href: lessons/01_intro.qmd
            text: "1. Introduction"
          - href: lessons/02_agent.qmd
            text: "2. Setting up the agent"

format:
  html:
    theme: [cosmo, custom.scss]
    toc: true
    code-overflow: wrap
