---
title: "AI-Assisted coding for research"
---

:::{.callout-warning} 

This is a new and **very experimental** workshop. Lesson materials are being
actively developed and may change!

:::

This hands-on three half-day workshop covers AI-assisted coding techniques with
an emphasis on research data analysis, reproducibility, and best practices of
Open Science. Learners will use real-world scenarios to explore concepts and
capabilities of coding agents and other LLM-based techniques. Workshop
activities touch on many aspects of the research lifecycle: from data discovery
and access, to visualization and publication.  

This is an experimental workshop covering a very new and rapidly evolving
landscape. **Coding agent sandboxes and LLM API access will be provided to
participants.** As a prerequisite, learners should have familiarity with a
programming language.

## Schedule

| Day | Topics |
|:---|:---| 
| **Day 1** | [Introduction](lessons/01_intro.qmd) <br /> [Getting Started with an Agent](lessons/02_agent.qmd) <br /> [Planning Mode](lessons/03_planning.qmd) |
| **Day 2** | Review <br /> Project structure & `AGENTS.md` <br /> Workflows <br /> Project work and report out |
| **Day 3** | Review <br /> Sharing / publishing <br /> Agents Skills <br /> Project work and report out |

## Contributors

- Julien Brun
- Seth Erickson
- Jon Jablonski
- Li Kui
- Jairo Melo-Flórez
- Jose Nino Muriel