---
title: "The bikeability of the Santa Barbara County"
---

## Use case: Computing the bikeability of the Santa Barbara County using terrain

Our goal is to develop a bikeability index to estimate how bike-friendly a specific area is. Here, we will focus on computing one component of this index by estimating the steepness of a specific area.

### Workflow overview

1.  Download a Digital Elevation Model (DEM) Covering Santa Barbara County
2.  Compute the slope from this DEM
3.  Calculate zonal statistics on the slope using the US Census Group Blocks for the area
4.  Create a Map showing the median slope for each area
5.  Share our project on GitHub

### Data

- DEM: we will get this dataset using the [STAC API](https://stacspec.org/en/) from data catalog of the Microsoft Planetary Computer <https://planetarycomputer.microsoft.com/catalog#DEMs>; we will use the `ALOS World 3D-30m` product, see <https://planetarycomputer.microsoft.com/api/stac/v1/collections/alos-dem>
- US Census group block: the dataset is available on the US Census Bureau server: <https://www2.census.gov/geo/tiger/TIGER2020/BG/> 

### Ask

- Work with your coding agent to refine the various steps you will need to complete your task
- Set up your project file structure organizing data (raw and processed), code, and visual outputs
- Remember that geospatial datasets can come in different projections
- Use Python or R to implement this workflow. 
  - When using Python, favor geopandas and pangeo libraries (https://pangeo.io/#ecosystem)
  - When using R, favor recent geospatial packages such as `sf` and `terra` and the tidyverse style guide
- Make sure to document your work well (code, data, outputs, ...)

::: {.callout-tip}
## Things to think about

- Start in Plan Mode to develop your workflow
- Request separate scripts for each major step of your workflow
- Think about how you would like to organize your data (raw, derived, ...)
- Think about managing your computing environment and to specify which libraries you would like to use
- Version control your work
- Initialize `AGENTS.md`  and keep it up-to-date
- Did we mention to document your work?!
::: 

### Going further

- Could you make your map interactive?
- Is the Census Group Block the best spatial unit?
- Any other zonal statistics that could be computed (e.g. maximum slope)?
- What other information could you add to our bikeability index? See references for ideas... or brainstorm with your agent!


### References

- Codina O, Maciejewska M, Nadal J, Marquet O. Built environment bikeability as a predictor of cycling frequency: Lessons from Barcelona. Transportation Research Interdisciplinary Perspectives. 2022;16: 100725. [doi:10.1016/j.trip.2022.100725](https://doi.org/10.1016/j.trip.2022.100725)
- Reading Data from the STAC API <https://planetarycomputer.microsoft.com/docs/quickstarts/reading-stac/>
